// Copyright (C) 2025, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.

/**
 * emit.ts — the TypeScript code target for the TS-native zapgen.
 *
 * Ported from the canonical Go zapgen TS emitter
 * (github.com/zap-proto/go/cmd/zapgen/emit_ts.go). The struct View + Builder
 * emission is byte-for-byte the same surface (same offsets, same fixed-section
 * size, same variable-tail encoding), so a buffer built by the generated Go
 * builder is readable by the generated TS view and vice versa. The generated
 * code imports the runtime from "@zap-proto/zap" (the published npm package),
 * not "@hanzo/zap".
 *
 * ADDED here: `interface` emission. Each declared interface codegens a typed
 * Client class (one async method per declared method), a typed abstract Server
 * class, and a method-ordinal table — ADDITIVE, the struct emission is
 * unchanged.
 */

import { TypeKind, kindName, slotSize } from "./schema.js";
import type {
  File,
  Struct,
  Field,
  Type,
  Interface,
  Method,
} from "./schema.js";

/** lowerFirst lowercases the first character. */
function lowerFirst(s: string): string {
  if (s === "") return s;
  const c = s[0];
  if (c >= "A" && c <= "Z") return c.toLowerCase() + s.slice(1);
  return s;
}
const camelLower = lowerFirst;

/** structSize is the high-water mark of every field's [offset, offset+size). */
function structSize(s: Struct): number {
  let size = 0;
  for (const f of s.fields) {
    const end = f.offset + slotSize(f.type);
    if (end > size) size = end;
  }
  return size;
}

/** validate checks field offsets do not overlap and types are supported. */
function validate(s: Struct): void {
  const size = structSize(s);
  if (size === 0) throw new Error(`struct ${s.name}: no fields`);
  const owner = new Array<string>(size).fill("");
  for (const f of s.fields) {
    const sz = slotSize(f.type);
    if (sz === 0) {
      throw new Error(
        `struct ${s.name} field ${f.name}: unsupported type ${kindName(f.type.kind)}`,
      );
    }
    if (f.offset < 0) {
      throw new Error(
        `struct ${s.name} field ${f.name}: negative offset ${f.offset}`,
      );
    }
    for (let i = 0; i < sz; i++) {
      const pos = f.offset + i;
      if (owner[pos] !== "") {
        throw new Error(
          `struct ${s.name}: field ${f.name} at offset ${pos} overlaps field ${owner[pos]}`,
        );
      }
      owner[pos] = f.name;
    }
  }
}

function fileHasList(f: File): boolean {
  return f.structs.some((s) => s.fields.some((fl) => fl.type.kind === TypeKind.List));
}

function sortedAliasNames(f: File): string[] {
  return [...f.aliases.keys()].sort();
}

/** tsInputType returns the TS type used in a struct Input interface. */
function tsInputType(t: Type): string {
  switch (t.kind) {
    case TypeKind.Bool:
      return "boolean";
    case TypeKind.U8:
    case TypeKind.U16:
    case TypeKind.U32:
    case TypeKind.I8:
    case TypeKind.I16:
    case TypeKind.I32:
    case TypeKind.F32:
    case TypeKind.F64:
      return "number";
    case TypeKind.U64:
    case TypeKind.I64:
      return "bigint";
    case TypeKind.Text:
      return "string";
    case TypeKind.Bytes:
    case TypeKind.BytesFixed:
      return "Uint8Array";
    case TypeKind.List:
      return "Uint8Array[]";
    case TypeKind.Struct:
      return "Uint8Array";
    default:
      return "unknown";
  }
}

/**
 * EmitTS emits one combined .ts file containing every struct's View + Builder
 * and every interface's Client + Server. Returns [basename, source].
 */
export function emitTS(f: File): [string, string] {
  if (f.structs.length === 0 && f.interfaces.length === 0) {
    throw new Error("no structs or interfaces to emit");
  }
  let source = f.source;
  if (source === "") source = f.package + ".zap";
  let base = source;
  const dot = base.lastIndexOf(".");
  if (dot >= 0) base = base.slice(0, dot);
  const outName = base + "_zap.ts";

  const w: string[] = [];
  w.push("// Code generated by zapgen --target=ts; DO NOT EDIT.\n");
  w.push(`// source: ${source}\n\n`);

  // Import only what the emitted code references, so the file type-checks under
  // strict noUnusedLocals.
  const needsStructRuntime = f.structs.length > 0;
  const needsService = f.interfaces.length > 0;
  w.push("import {\n");
  if (needsStructRuntime) {
    w.push("  Builder,\n");
    w.push("  Message,\n");
    w.push("  StructView,\n");
    if (fileHasList(f)) w.push("  type ListView,\n");
  }
  if (needsService) {
    // Only the helpers the emitted Client/Server reference, so the generated
    // file type-checks under strict noUnusedLocals. (parseResponse is not used:
    // the Client awaits a decoded Response from its channel, it never decodes
    // an envelope itself.)
    w.push("  buildRequest,\n");
    w.push("  parseRequest,\n");
    w.push("  buildResponse,\n");
    w.push("  NO_TARGET,\n");
    w.push("  Status,\n");
    w.push("  type Call,\n");
    w.push("  type Response,\n");
  }
  w.push('} from "@zap-proto/zap";\n\n');

  emitTSAliases(w, f);

  for (const s of f.structs) {
    validate(s);
    emitTSOffsets(w, s);
    emitTSView(w, s);
    emitTSBuilder(w, s);
    w.push("\n");
  }

  for (const iface of f.interfaces) {
    emitTSInterface(w, iface);
    w.push("\n");
  }

  return [outName, w.join("")];
}

function emitTSAliases(w: string[], f: File): void {
  let wrote = false;
  for (const name of sortedAliasNames(f)) {
    const t = f.aliases.get(name)!;
    if (t.kind !== TypeKind.BytesFixed) continue;
    w.push(
      `export type ${name} = Uint8Array & { readonly __brand: ${JSON.stringify(name)} };\n`,
    );
    wrote = true;
  }
  if (wrote) w.push("\n");
}

function emitTSOffsets(w: string[], s: Struct): void {
  const lower = lowerFirst(s.name);
  w.push(`const ${lower}Off = {\n`);
  for (const f of s.fields) w.push(`  ${f.name}: ${f.offset},\n`);
  w.push("} as const;\n");
  w.push(`const ${lower}Size = ${structSize(s)};\n\n`);
}

function emitTSView(w: string[], s: Struct): void {
  const lower = lowerFirst(s.name);
  w.push(`/** Zero-copy view into a ZAP-encoded ${s.name} message. */\n`);
  w.push(`export class ${s.name} extends StructView {\n`);
  w.push(
    "  /** Parse `b` and return a typed view. Throws on a wire-level check failure (magic, version, size). */\n",
  );
  w.push(`  static wrap(b: Uint8Array): ${s.name} {\n`);
  w.push("    const root = Message.parse(b).root();\n");
  w.push(`    return new ${s.name}(root.data, root.offset);\n`);
  w.push("  }\n\n");
  for (const f of s.fields) emitTSFieldGetter(w, lower, f);
  w.push("}\n\n");
}

function emitTSFieldGetter(w: string[], lower: string, f: Field): void {
  const off = `${lower}Off.${f.name}`;
  const n = camelLower(f.name);
  switch (f.type.kind) {
    case TypeKind.Bool:
      w.push(`  get ${n}(): boolean { return this.bool(${off}); }\n`);
      break;
    case TypeKind.U8:
      w.push(`  get ${n}(): number { return this.u8(${off}); }\n`);
      break;
    case TypeKind.U16:
      w.push(`  get ${n}(): number { return this.u16(${off}); }\n`);
      break;
    case TypeKind.U32:
      w.push(`  get ${n}(): number { return this.u32(${off}); }\n`);
      break;
    case TypeKind.U64:
      w.push(`  get ${n}(): bigint { return this.u64(${off}); }\n`);
      break;
    case TypeKind.I8:
      w.push(`  get ${n}(): number { return this.i8(${off}); }\n`);
      break;
    case TypeKind.I16:
      w.push(`  get ${n}(): number { return this.i16(${off}); }\n`);
      break;
    case TypeKind.I32:
      w.push(`  get ${n}(): number { return this.i32(${off}); }\n`);
      break;
    case TypeKind.I64:
      w.push(`  get ${n}(): bigint { return this.i64(${off}); }\n`);
      break;
    case TypeKind.F32:
      w.push(`  get ${n}(): number { return this.f32(${off}); }\n`);
      break;
    case TypeKind.F64:
      w.push(`  get ${n}(): number { return this.f64(${off}); }\n`);
      break;
    case TypeKind.Text:
      w.push(`  get ${n}(): string { return this.text(${off}); }\n`);
      break;
    case TypeKind.Bytes:
      w.push(`  get ${n}(): Uint8Array { return this.bytes(${off}); }\n`);
      break;
    case TypeKind.BytesFixed:
      w.push(
        `  get ${n}(): Uint8Array { return this.bytesFixed(${off}, ${f.type.fixedSize}); }\n`,
      );
      break;
    case TypeKind.List:
      w.push(`  get ${n}(): ListView { return this.list(${off}); }\n`);
      break;
    case TypeKind.Struct:
      w.push(`  get ${n}(): ${f.type.structName} {\n`);
      w.push(`    const o = this.object(${off});\n`);
      w.push(`    return new ${f.type.structName}(o.data, o.offset);\n`);
      w.push("  }\n");
      break;
  }
}

function emitTSBuilder(w: string[], s: Struct): void {
  const lower = lowerFirst(s.name);
  w.push(`/** Field values for new${s.name}. */\n`);
  w.push(`export interface ${s.name}Input {\n`);
  for (const f of s.fields) {
    w.push(`  ${camelLower(f.name)}: ${tsInputType(f.type)};\n`);
  }
  w.push("}\n\n");

  w.push(`/** Build a ZAP-encoded ${s.name} message from \`in\` and return the bytes. */\n`);
  w.push(`export function new${s.name}(in_: ${s.name}Input): Uint8Array {\n`);
  w.push("  const b = new Builder(256);\n");
  w.push(`  const ob = b.startObject(${lower}Size);\n`);
  for (const f of s.fields) emitTSFieldWriter(w, lower, f);
  w.push("  ob.finishAsRoot();\n");
  w.push("  return b.finish();\n");
  w.push("}\n\n");
}

function emitTSFieldWriter(w: string[], lower: string, f: Field): void {
  const off = `${lower}Off.${f.name}`;
  const name = camelLower(f.name);
  switch (f.type.kind) {
    case TypeKind.Bool:
      w.push(`  ob.setBool(${off}, in_.${name});\n`);
      break;
    case TypeKind.U8:
      w.push(`  ob.setU8(${off}, in_.${name});\n`);
      break;
    case TypeKind.U16:
      w.push(`  ob.setU16(${off}, in_.${name});\n`);
      break;
    case TypeKind.U32:
      w.push(`  ob.setU32(${off}, in_.${name});\n`);
      break;
    case TypeKind.U64:
      w.push(`  ob.setU64(${off}, in_.${name});\n`);
      break;
    case TypeKind.I8:
      w.push(`  ob.setI8(${off}, in_.${name});\n`);
      break;
    case TypeKind.I16:
      w.push(`  ob.setI16(${off}, in_.${name});\n`);
      break;
    case TypeKind.I32:
      w.push(`  ob.setI32(${off}, in_.${name});\n`);
      break;
    case TypeKind.I64:
      w.push(`  ob.setI64(${off}, in_.${name});\n`);
      break;
    case TypeKind.F32:
      w.push(`  ob.setF32(${off}, in_.${name});\n`);
      break;
    case TypeKind.F64:
      w.push(`  ob.setF64(${off}, in_.${name});\n`);
      break;
    case TypeKind.Text:
      w.push(`  ob.setText(${off}, in_.${name});\n`);
      break;
    case TypeKind.Bytes:
      w.push(`  ob.setBytes(${off}, in_.${name});\n`);
      break;
    case TypeKind.BytesFixed:
      w.push(`  ob.setBytesFixed(${off}, in_.${name});\n`);
      break;
    case TypeKind.List: {
      const listVar = name + "LB";
      w.push(`  const ${listVar} = b.startList();\n`);
      w.push(`  for (const elem of in_.${name}) ${listVar}.addObjectBytes(elem);\n`);
      w.push(`  ob.setList(${off}, ${listVar}.finishOffset(), in_.${name}.length);\n`);
      break;
    }
    case TypeKind.Struct:
      w.push(`  if (in_.${name}.length > 0) {\n`);
      w.push(`    const nested = b.startObject(in_.${name}.length);\n`);
      w.push(`    nested.setBytesFixed(0, in_.${name});\n`);
      w.push(`    ob.setObject(${off}, nested.finish());\n`);
      w.push("  }\n");
      break;
  }
}

// --- service emission (ADDED — interface → Client + Server + ordinal table) --

/**
 * emitTSInterface emits, for one interface:
 *   - a method-ordinal const table (`<Iface>Method`)
 *   - a typed Client class (one async method per declared method)
 *   - a typed abstract Server class (one abstract handler per method) plus a
 *     `dispatch(call)` that decodes the ordinal and routes to the handler.
 *
 * Ordinals are 1, 2, 3, ... by declaration order, baked from the AST so the
 * wire ordinal never shifts when a method is appended.
 */
function emitTSInterface(w: string[], iface: Interface): void {
  // Ordinal table.
  w.push(`/** Method ordinals for the ${iface.name} service (stable wire ids). */\n`);
  w.push(`export const ${iface.name}Method = {\n`);
  for (const m of iface.methods) {
    w.push(`  ${camelLower(m.name)}: ${m.ordinal},\n`);
  }
  w.push("} as const;\n\n");

  emitTSClient(w, iface);
  emitTSServer(w, iface);
}

/** reqType returns the TS arg type for a method's request param. */
function reqArg(m: Method): string {
  return m.request ? `${m.request.name}: Uint8Array` : "";
}

/** respType returns the TS return type for a method's response. */
function respType(m: Method): string {
  return m.response ? "Promise<Uint8Array>" : "Promise<void>";
}

function emitTSClient(w: string[], iface: Interface): void {
  w.push(
    `/** Typed RPC client for the ${iface.name} service over a ZAP call channel. */\n`,
  );
  w.push(`export interface ${iface.name}Channel {\n`);
  w.push(
    "  /** Ship one Call envelope and await its correlated Response. */\n",
  );
  w.push("  call(envelope: Uint8Array): Promise<Response>;\n");
  w.push("}\n\n");

  w.push(`export class ${iface.name}Client {\n`);
  w.push(`  constructor(private readonly channel: ${iface.name}Channel, private readonly cap: Uint8Array = new Uint8Array(0)) {}\n\n`);
  for (const m of iface.methods) {
    const mname = camelLower(m.name);
    w.push(`  async ${mname}(${reqArg(m)}): ${respType(m)} {\n`);
    const payload = m.request ? m.request.name : "new Uint8Array(0)";
    w.push(`    const envelope = buildRequest({\n`);
    w.push(`      method: ${iface.name}Method.${mname},\n`);
    w.push(`      promiseID: 0,\n`);
    w.push(`      target: NO_TARGET,\n`);
    w.push(`      cap: this.cap,\n`);
    w.push(`      payload: ${payload},\n`);
    w.push(`    });\n`);
    w.push(`    const resp = await this.channel.call(envelope);\n`);
    w.push(`    if (resp.status !== Status.OK) {\n`);
    w.push(`      throw new Error(\`${iface.name}.${mname}: status \${resp.status}\`);\n`);
    w.push(`    }\n`);
    if (m.response) {
      w.push(`    return resp.body;\n`);
    }
    w.push("  }\n\n");
  }
  w.push("}\n\n");
}

function emitTSServer(w: string[], iface: Interface): void {
  w.push(
    `/** Abstract RPC server for the ${iface.name} service. Subclass and implement each method. */\n`,
  );
  w.push(`export abstract class ${iface.name}Server {\n`);
  for (const m of iface.methods) {
    const mname = camelLower(m.name);
    const arg = m.request ? `${m.request.name}: Uint8Array` : "";
    const ret = m.response ? "Promise<Uint8Array>" : "Promise<void>";
    w.push(`  abstract ${mname}(${arg}): ${ret};\n`);
  }
  w.push("\n");
  // dispatch: decode the request, route by ordinal, build the response.
  w.push(
    "  /** Decode a Call envelope, route by method ordinal, and build the Response envelope. */\n",
  );
  w.push("  async dispatch(envelope: Uint8Array): Promise<Uint8Array> {\n");
  w.push("    const call: Call = parseRequest(envelope);\n");
  w.push("    switch (call.method) {\n");
  for (const m of iface.methods) {
    const mname = camelLower(m.name);
    w.push(`      case ${iface.name}Method.${mname}: {\n`);
    if (m.request && m.response) {
      w.push(`        const body = await this.${mname}(call.payload);\n`);
      w.push(`        return buildResponse(Status.OK, call.promiseID, body);\n`);
    } else if (m.request && !m.response) {
      w.push(`        await this.${mname}(call.payload);\n`);
      w.push(`        return buildResponse(Status.OK, call.promiseID, new Uint8Array(0));\n`);
    } else if (!m.request && m.response) {
      w.push(`        const body = await this.${mname}();\n`);
      w.push(`        return buildResponse(Status.OK, call.promiseID, body);\n`);
    } else {
      w.push(`        await this.${mname}();\n`);
      w.push(`        return buildResponse(Status.OK, call.promiseID, new Uint8Array(0));\n`);
    }
    w.push("      }\n");
  }
  w.push("      default:\n");
  w.push("        return buildResponse(Status.NotFound, call.promiseID, new Uint8Array(0));\n");
  w.push("    }\n");
  w.push("  }\n");
  w.push("}\n\n");
}
